thermal_diffusivity:
  name: Thermal diffusivity
  description: Thermal diffusivity
  value:
    type: float
    default: 0.75
    range:
      min: 0.0
      max: 10.0
    units: 'm2 s-1'

number_of_rows:
  name: Number of rows
  description: Number of grid rows
  value:
    type: int
    default: 8
    range:
      min: 0
      max: 10000
    units: '1'

number_of_columns:
  name: Number of columns
  description: Number of grid columns
  value:
    type: int
    default: 6
    range:
      min: 0
      max: 10000
    units: '1'

spacing_x:
  description: Grid spacing in x-direction
  value:
    type: float
    default: 1.0
    units: m
    range:
      min: 1E-6
      max: 1E6

spacing_y:
  description: Grid spacing in y-direction
  value:
    type: float
    default: 1.0
    units: m
    range:
      min: 1E-6
      max: 1E6

origin_x:
  description: Location of grid origin in x-direction
  value:
    type: float
    default: 0.0
    units: m
    range:
      min: 1E-6
      max: 1E6

origin_y:
  description: Locationh of grid origin in y-direction
  value:
    type: float
    default: 0.0
    units: m
    range:
      min: 1E-6
      max: 1E6
